/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_v1_admin_companies_get"];
        put?: never;
        /** Create Company */
        post: operations["create_company_api_v1_admin_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/companies/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Company */
        get: operations["get_my_company_api_v1_admin_companies_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Company */
        patch: operations["update_my_company_api_v1_admin_companies_me_patch"];
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/track/{tracking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Parcel */
        get: operations["track_parcel_api_v1_track__tracking_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Parcels */
        get: operations["list_parcels_api_v1_parcels_get"];
        put?: never;
        /** Create Parcel */
        post: operations["create_parcel_api_v1_parcels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Load Parcel */
        patch: operations["load_parcel_api_v1_parcels_load_patch"];
        trace?: never;
    };
    "/api/v1/parcels/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Unload Parcel Endpoint */
        patch: operations["unload_parcel_endpoint_api_v1_parcels_unload_patch"];
        trace?: never;
    };
    "/api/v1/parcels/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Collect Parcel Endpoint */
        post: operations["collect_parcel_endpoint_api_v1_parcels_collect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parcels/{parcel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Parcel */
        get: operations["get_parcel_api_v1_parcels__parcel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_v1_trips_get"];
        put?: never;
        /** Create Trip */
        post: operations["create_trip_api_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip Manifest */
        get: operations["get_trip_manifest_api_v1_trips__trip_id__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip_api_v1_trips__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Trip Status */
        patch: operations["update_trip_status_api_v1_trips__trip_id__status_patch"];
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle Booking */
        patch: operations["toggle_booking_api_v1_trips__trip_id__booking_patch"];
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_v1_tickets_get"];
        put?: never;
        /** Create Ticket */
        post: operations["create_ticket_api_v1_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/initiate-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate Payment */
        post: operations["initiate_payment_api_v1_tickets__ticket_id__initiate_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share Ticket
         * @description Send the passenger a link to view and download their ticket.
         */
        post: operations["share_ticket_api_v1_tickets__ticket_id__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stations */
        get: operations["list_stations_api_v1_stations_get"];
        put?: never;
        /** Create Station */
        post: operations["create_station_api_v1_stations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stations/{station_id}/pending-parcels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Parcels
         * @description Returns all parcels waiting at this station to be loaded onto a bus.
         *     Used by the Station Manager dashboard (the 'inventory view').
         */
        get: operations["get_pending_parcels_api_v1_stations__station_id__pending_parcels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vehicles */
        get: operations["list_vehicles_api_v1_vehicles_get"];
        put?: never;
        /** Create Vehicle */
        post: operations["create_vehicle_api_v1_vehicles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/paystack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paystack Webhook */
        post: operations["paystack_webhook_api_v1_webhooks_paystack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Public Trips
         * @description Return trips open for online booking.
         */
        get: operations["list_public_trips_api_v1_public_trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/trips/{trip_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Seat Map
         * @description Return capacity and list of taken seat numbers for a trip.
         */
        get: operations["get_seat_map_api_v1_public_trips__trip_id__seats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/trips/{trip_id}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Book Ticket
         * @description Passenger books a seat and gets a Paystack payment URL.
         */
        post: operations["book_ticket_api_v1_public_trips__trip_id__book_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Ticket
         * @description Passenger polls this after returning from Paystack payment flow.
         */
        get: operations["get_public_ticket_api_v1_public_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** BookRequest */
        BookRequest: {
            /** Passenger Name */
            passenger_name: string;
            /** Passenger Phone */
            passenger_phone: string;
            /** Seat Number */
            seat_number: number;
            /** Passenger Email */
            passenger_email?: string | null;
        };
        /** BookResponse */
        BookResponse: {
            /** Ticket Id */
            ticket_id: number;
            /** Authorization Url */
            authorization_url: string;
            /** Reference */
            reference: string;
        };
        /** CollectParcelRequest */
        CollectParcelRequest: {
            /** Tracking Number */
            tracking_number: string;
            /** Otp */
            otp: string;
        };
        /** CompanyCreate */
        CompanyCreate: {
            /** Name */
            name: string;
            /** Company Code */
            company_code: string;
            /** Subdomain */
            subdomain?: string | null;
            /** Brand Color */
            brand_color?: string | null;
        };
        /** CompanyResponse */
        CompanyResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Company Code */
            company_code: string;
            /** Subdomain */
            subdomain: string | null;
            /** Brand Color */
            brand_color: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** CompanyUpdate */
        CompanyUpdate: {
            /** Brand Color */
            brand_color?: string | null;
        };
        /** CreateParcelRequest */
        CreateParcelRequest: {
            /** Sender Name */
            sender_name: string;
            /** Sender Phone */
            sender_phone: string;
            /** Receiver Name */
            receiver_name: string;
            /** Receiver Phone */
            receiver_phone: string;
            /** Origin Station Id */
            origin_station_id: number;
            /** Destination Station Id */
            destination_station_id: number;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Description */
            description?: string | null;
            /**
             * Fee Ghs
             * @default 0
             */
            fee_ghs: number;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** CreateStationRequest */
        CreateStationRequest: {
            /** Name */
            name: string;
            /** Location Code */
            location_code?: string | null;
            /** Contact Number */
            contact_number?: string | null;
            /** Address */
            address?: string | null;
            /**
             * Is Hub
             * @default false
             */
            is_hub: boolean;
        };
        /** CreateTicketRequest */
        CreateTicketRequest: {
            /** Trip Id */
            trip_id: number;
            /** Passenger Name */
            passenger_name: string;
            /** Passenger Phone */
            passenger_phone: string;
            /** Seat Number */
            seat_number: number;
            /** Fare Ghs */
            fare_ghs: number;
        };
        /** CreateTripRequest */
        CreateTripRequest: {
            /** Vehicle Id */
            vehicle_id: number;
            /** Departure Station Id */
            departure_station_id: number;
            /** Destination Station Id */
            destination_station_id: number;
            /**
             * Departure Time
             * Format: date-time
             */
            departure_time: string;
            /** Base Fare Ghs */
            base_fare_ghs?: number | null;
            /**
             * Booking Open
             * @default false
             */
            booking_open: boolean;
        };
        /** CreateVehicleRequest */
        CreateVehicleRequest: {
            /** Plate Number */
            plate_number: string;
            /** Model */
            model?: string | null;
            /**
             * Capacity
             * @default 50
             */
            capacity: number;
            /** Home Station Id */
            home_station_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitiatePaymentRequest */
        InitiatePaymentRequest: {
            /** Email */
            email?: string | null;
        };
        /** InitiatePaymentResponse */
        InitiatePaymentResponse: {
            /** Authorization Url */
            authorization_url: string;
            /** Reference */
            reference: string;
        };
        /** LoadParcelRequest */
        LoadParcelRequest: {
            /** Tracking Number */
            tracking_number: string;
            /** Trip Id */
            trip_id: number;
        };
        /** ParcelResponse */
        ParcelResponse: {
            /** Id */
            id: number;
            /** Tracking Number */
            tracking_number: string;
            /** Status */
            status: string;
            /** Sender Name */
            sender_name: string;
            /** Receiver Name */
            receiver_name: string;
            /** Receiver Phone */
            receiver_phone: string;
            /** Origin Station Id */
            origin_station_id: number;
            /** Destination Station Id */
            destination_station_id: number;
            /** Origin Station Name */
            origin_station_name?: string | null;
            /** Destination Station Name */
            destination_station_name?: string | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Fee Ghs */
            fee_ghs: number;
            /** Description */
            description?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Qr Code Base64 */
            qr_code_base64?: string | null;
        };
        /** PendingParcelSummary */
        PendingParcelSummary: {
            /** Tracking Number */
            tracking_number: string;
            /** Receiver Name */
            receiver_name: string;
            /** Destination */
            destination: string;
            /** Fee Ghs */
            fee_ghs: number;
        };
        /** PublicParcelStatus */
        PublicParcelStatus: {
            /** Tracking Number */
            tracking_number: string;
            /** Status */
            status: string;
            /** Origin */
            origin: string;
            /** Destination */
            destination: string;
            /** Bus Plate */
            bus_plate?: string | null;
            /** Last Updated */
            last_updated: string;
        };
        /** PublicTicketResponse */
        PublicTicketResponse: {
            /** Id */
            id: number;
            /** Passenger Name */
            passenger_name: string;
            /** Seat Number */
            seat_number: number;
            /** Fare Ghs */
            fare_ghs: number;
            /** Status */
            status: string;
            /** Payment Status */
            payment_status: string;
            /** Departure Station */
            departure_station: string | null;
            /** Destination Station */
            destination_station: string | null;
            /** Departure Time */
            departure_time: string | null;
            /** Vehicle Plate */
            vehicle_plate: string | null;
            /** Company Name */
            company_name: string | null;
            /** Brand Color */
            brand_color: string | null;
        };
        /** PublicTripResponse */
        PublicTripResponse: {
            /** Id */
            id: number;
            /** Departure Station Name */
            departure_station_name: string;
            /** Destination Station Name */
            destination_station_name: string;
            /** Departure Time */
            departure_time: string;
            /** Vehicle Capacity */
            vehicle_capacity: number;
            /** Available Seat Count */
            available_seat_count: number;
            /** Price Ghs */
            price_ghs: number | null;
            /** Company Name */
            company_name: string;
            /** Brand Color */
            brand_color: string | null;
        };
        /** SeatMapResponse */
        SeatMapResponse: {
            /** Capacity */
            capacity: number;
            /** Taken */
            taken: number[];
        };
        /** ShareTicketRequest */
        ShareTicketRequest: {
            /** Phone */
            phone: string;
        };
        /** ShareTicketResponse */
        ShareTicketResponse: {
            /** Url */
            url: string;
            /** Sms Sent */
            sms_sent: boolean;
        };
        /** StationResponse */
        StationResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Location Code */
            location_code: string | null;
            /** Contact Number */
            contact_number: string | null;
            /** Address */
            address: string | null;
            /** Is Hub */
            is_hub: boolean;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * TicketDetailResponse
         * @description Enriched response used by the print/detail view.
         */
        TicketDetailResponse: {
            /** Id */
            id: number;
            /** Trip Id */
            trip_id: number;
            /** Passenger Name */
            passenger_name: string;
            /** Passenger Phone */
            passenger_phone: string;
            /** Seat Number */
            seat_number: number;
            /** Fare Ghs */
            fare_ghs: number;
            /** Status */
            status: string;
            /** Payment Status */
            payment_status: string;
            /**
             * Source
             * @default counter
             */
            source: string;
            /** Company Name */
            company_name?: string | null;
            /** Brand Color */
            brand_color?: string | null;
            /** Departure Station */
            departure_station?: string | null;
            /** Destination Station */
            destination_station?: string | null;
            /** Departure Time */
            departure_time?: string | null;
            /** Vehicle Plate */
            vehicle_plate?: string | null;
        };
        /** TicketResponse */
        TicketResponse: {
            /** Id */
            id: number;
            /** Trip Id */
            trip_id: number;
            /** Passenger Name */
            passenger_name: string;
            /** Passenger Phone */
            passenger_phone: string;
            /** Seat Number */
            seat_number: number;
            /** Fare Ghs */
            fare_ghs: number;
            /** Status */
            status: string;
            /** Payment Status */
            payment_status: string;
            /**
             * Source
             * @default counter
             */
            source: string;
        };
        /** ToggleBookingRequest */
        ToggleBookingRequest: {
            /** Booking Open */
            booking_open: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TripResponse */
        TripResponse: {
            /** Id */
            id: number;
            /** Vehicle Id */
            vehicle_id: number;
            /** Departure Station Id */
            departure_station_id: number;
            /** Destination Station Id */
            destination_station_id: number;
            /**
             * Departure Time
             * Format: date-time
             */
            departure_time: string;
            /** Status */
            status: string;
            /**
             * Booking Open
             * @default false
             */
            booking_open: boolean;
            /** Price Ticket Base */
            price_ticket_base?: number | null;
            /** Vehicle Plate */
            vehicle_plate?: string | null;
            /** Vehicle Capacity */
            vehicle_capacity?: number | null;
            /** Departure Station Name */
            departure_station_name?: string | null;
            /** Destination Station Name */
            destination_station_name?: string | null;
            /**
             * Parcel Count
             * @default 0
             */
            parcel_count: number;
            /**
             * Tickets Sold
             * @default 0
             */
            tickets_sold: number;
            /**
             * Occupancy Pct
             * @default 0
             */
            occupancy_pct: number;
            /**
             * Is Near Full
             * @default false
             */
            is_near_full: boolean;
        };
        /**
         * TripStatus
         * @enum {string}
         */
        TripStatus: "scheduled" | "loading" | "departed" | "arrived" | "cancelled";
        /** UnloadParcelRequest */
        UnloadParcelRequest: {
            /** Parcel Id */
            parcel_id: number;
        };
        /** UpdateTripStatusRequest */
        UpdateTripStatusRequest: {
            status: components["schemas"]["TripStatus"];
        };
        /** UserCreate */
        UserCreate: {
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email?: string | null;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
            /** Station Id */
            station_id?: number | null;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Role */
            role: string;
            /** Company Id */
            company_id: number | null;
            /** Station Id */
            station_id: number | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Role */
            role: string;
            /** Company Id */
            company_id: number | null;
            /** Station Id */
            station_id: number | null;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "super_admin" | "company_admin" | "station_manager" | "station_clerk";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VehicleResponse */
        VehicleResponse: {
            /** Id */
            id: number;
            /** Plate Number */
            plate_number: string;
            /** Model */
            model: string | null;
            /** Capacity */
            capacity: number;
            /** Is Active */
            is_active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_companies_api_v1_admin_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"][];
                };
            };
        };
    };
    create_company_api_v1_admin_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_company_api_v1_admin_companies_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
        };
    };
    update_my_company_api_v1_admin_companies_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_parcel_api_v1_track__tracking_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tracking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicParcelStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_parcels_api_v1_parcels_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_parcel_api_v1_parcels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateParcelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_parcel_api_v1_parcels_load_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadParcelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unload_parcel_endpoint_api_v1_parcels_unload_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnloadParcelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    collect_parcel_endpoint_api_v1_parcels_collect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectParcelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_parcel_api_v1_parcels__parcel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                parcel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips_api_v1_trips_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TripStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trip_api_v1_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_manifest_api_v1_trips__trip_id__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip_api_v1_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_status_api_v1_trips__trip_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_booking_api_v1_trips__trip_id__booking_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleBookingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_v1_tickets_get: {
        parameters: {
            query?: {
                trip_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_api_v1_tickets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    initiate_payment_api_v1_tickets__ticket_id__initiate_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiatePaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitiatePaymentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_v1_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_ticket_api_v1_tickets__ticket_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareTicketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareTicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stations_api_v1_stations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationResponse"][];
                };
            };
        };
    };
    create_station_api_v1_stations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_parcels_api_v1_stations__station_id__pending_parcels_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingParcelSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vehicles_api_v1_vehicles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"][];
                };
            };
        };
    };
    create_vehicle_api_v1_vehicles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    paystack_webhook_api_v1_webhooks_paystack_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_public_trips_api_v1_public_trips_get: {
        parameters: {
            query?: {
                from_station_id?: number | null;
                to_station_id?: number | null;
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicTripResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seat_map_api_v1_public_trips__trip_id__seats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatMapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_ticket_api_v1_public_trips__trip_id__book_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_ticket_api_v1_public_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicTicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
