"""add token_version to users

Revision ID: 0e34c655efa3
Revises: 0020
Create Date: 2026-04-09 10:24:06.693576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e34c655efa3'
down_revision: Union[str, None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_parcel_company_status'), table_name='parcels')
    op.drop_index(op.f('idx_parcel_origin_station'), table_name='parcels')
    op.drop_index(op.f('idx_parcel_receiver_phone'), table_name='parcels')
    op.drop_index(op.f('idx_parcel_tracking'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_created_by_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_current_trip_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_destination_station_id'), table_name='parcels')
    op.drop_index(op.f('ix_payment_events_ticket_id'), table_name='payment_events')
    op.drop_index(op.f('ix_sms_logs_parcel_id'), table_name='sms_logs')
    op.alter_column('stations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_ticket_trip_seat'), table_name='tickets', postgresql_where="(status <> 'cancelled'::ticketstatus)")
    op.drop_index(op.f('ix_ticket_booking_expires_at'), table_name='tickets')
    op.drop_index(op.f('ix_ticket_payment_ref'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_by_id'), table_name='tickets')
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_trip_company_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_departure_station_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination_station_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_user_company'), table_name='users')
    op.drop_index(op.f('ix_users_station_id'), table_name='users')
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_webhook_event_unprocessed'), table_name='webhook_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_webhook_event_unprocessed'), 'webhook_events', ['processed_at'], unique=False)
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_station_id'), 'users', ['station_id'], unique=False)
    op.create_index(op.f('idx_user_company'), 'users', ['company_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'token_version')
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_trips_destination_station_id'), 'trips', ['destination_station_id'], unique=False)
    op.create_index(op.f('ix_trips_departure_station_id'), 'trips', ['departure_station_id'], unique=False)
    op.create_index(op.f('idx_trip_company_status'), 'trips', ['company_id', 'status'], unique=False)
    op.alter_column('trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tickets_created_by_id'), 'tickets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_ticket_payment_ref'), 'tickets', ['payment_ref'], unique=False)
    op.create_index(op.f('ix_ticket_booking_expires_at'), 'tickets', ['booking_expires_at'], unique=False)
    op.create_index(op.f('idx_ticket_trip_seat'), 'tickets', ['trip_id', 'seat_number'], unique=True, postgresql_where="(status <> 'cancelled'::ticketstatus)")
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_sms_logs_parcel_id'), 'sms_logs', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_payment_events_ticket_id'), 'payment_events', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_parcels_destination_station_id'), 'parcels', ['destination_station_id'], unique=False)
    op.create_index(op.f('ix_parcels_current_trip_id'), 'parcels', ['current_trip_id'], unique=False)
    op.create_index(op.f('ix_parcels_created_by_id'), 'parcels', ['created_by_id'], unique=False)
    op.create_index(op.f('idx_parcel_tracking'), 'parcels', ['tracking_number'], unique=False)
    op.create_index(op.f('idx_parcel_receiver_phone'), 'parcels', ['receiver_phone'], unique=False)
    op.create_index(op.f('idx_parcel_origin_station'), 'parcels', ['origin_station_id', 'status'], unique=False)
    op.create_index(op.f('idx_parcel_company_status'), 'parcels', ['company_id', 'status'], unique=False)
    op.alter_column('parcels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parcels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
